### ISSUE TITLE
Cannot set right hand side for inequalities with a convex quadratic expression

### ISSUE THREAD

**Issue by haoxiangyang89** [JuliaOpt/JuMP.jl#1017]
Is it possible to change the right hand side of an inequality like $x^\top Q x \leq 0$ with Q positive semidefinite? I tried using `JuMP.setRHS` but it seems not accepting the quadratic constraint. Error message attached:
```julia
ERROR: MethodError: no method matching setRHS(::JuMP.ConstraintRef{JuMP.Model,JuMP.GenericQuadConstraint{JuMP.GenericQuadExpr{Float64,JuMP.Variable}}}, ::Float64)
```

**Comment by joehuchette** [comment]
The problem is that our internal representation does not store the RHS constant separately from any constant on the LHS, so for example ``x - 1 >= 0`` and ``x >= 1`` are stored the same way. We've discussed this in the past, but haven't been able to come up with a good solution.

There are hacky ways to change the problem data if you really want to, but it's probably best to rebuild the model from scratch, unless model generation is truly a bottleneck.

**Comment by mlubin** [comment]
``JuMP.setRHS`` is broken (https://github.com/JuliaOpt/JuMP.jl/issues/470). Use fixed variables instead, and fix them to new values to achieve the same result as changing the RHS.
