### ISSUE TITLE
Accessing the expression

### ISSUE THREAD

**Issue by kaarthiksundar** [JuliaOpt/JuMP.jl#1109]
I create a JuMP model within a function and return the model. Within the model, expressions are created using the ``@expression`` macro. Where in the model can I find a dictionary of created expressions?

Thanks

**Comment by mlubin** [comment]
These are not currently stored anywhere, but you can add them to the model with `m[:foo] = ...` and access them later as `m[:foo]`, for example. I'll leave this open so we revisit this issue after the MOI rewrite since I'd agree that it would be consistent to automatically store these expressions in the scope of the model.

**Comment by bbrunaud** [comment]
+1
