### ISSUE TITLE
Handling custom constraint types

### ISSUE THREAD

**Issue by rdeits** [JuliaOpt/JuMP.jl#1152]
(carried over from discussion on gitter)

How should we handle custom constraint types (custom MOI functions or sets) that users might want to add to a model? For example, if I want to make a `Complementarity` `AbstractSet` and add it to my model, how should i go about that? The current design doesn't allow this, because the set of function and set types is fixed in the definition of `JuMPInstance`. 

I can see a couple of options:

1. Store the instance constraints in a container with an abstract type, so that users can add whatever types they want
2. Ask users to create their own instance type using the `@MOI.instance` macro

Option 1 seems likely to be easier, but may have performance issues. But I would be interested in benchmarking that before making any assumptions. 

Another way of implementing (1) would be to have a field with the (abstract) type `::TypeSortedCollection` using https://github.com/tkoolen/TypeSortedCollections.jl and update that field as constraints are added to the model. Accessing that field would not be type-stable, but iterating over it would still be fast.

**Comment by mlubin** [comment]
I was never too happy with needing to declare the sets and functions ahead of time. What we basically need is a container that can map a tuple of MOI function `F` and MOI set `S` to an object that stores a `Vector{Tuple{F,S}}` of constraints plus some attributes tacked on. It could be just a `Dict`... the initial implementation does not need to be super fast, but eventually we'd need to benchmark and make sure that we're not paying a high price for the extra flexibility in the container.

TypeSortedCollections has the right idea but it isn't exactly what we need. It seems like it's not designed to handle the case of dynamically elements of a new type to the collection. 

@blegat

**Comment by rdeits** [comment]
I mocked up a few options in https://github.com/rdeits/jump-containers/blob/master/containers.jl

Using julia 0.7.0-DEV.3018 I get the following results (`SpecializedContainer` is roughly what JuMP master is using):

```
container = SpecializedContainer
  1.012 μs (12 allocations: 4.58 KiB)
container = TypeContainer
  6.706 μs (15 allocations: 4.81 KiB)
container = IDContainer
  5.283 μs (16 allocations: 4.84 KiB)
container = IDVectContainer
  3.763 μs (18 allocations: 4.97 KiB)
container = ErasedContainer
  1.324 μs (114 allocations: 5.69 KiB)
```

**Comment by blegat** [comment]
Having custom constraints is something I have been thinking about for quite a while. One other application than Indicator Constraints that has been talked about is [SumOfSquares constraints](https://github.com/JuliaOpt/MathOptInterface.jl/issues/183). As you discussed on Gitter, it would be nice if the solvers that can handle indicator constraints get the constraint as is and for other solvers, the constrained is transform by adding new binary variables and big-M linear constraints (similar story for the SOS cone). This can be achieved through bridges (see a simple example [here](https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/blob/master/src/intervalbridge.jl)). If you define the transformation of indicator constraints to binary variable + big-M linear constraint as a bridge, it would allow solvers supporting binary variables to also support indicator constraints.
Currently, bridges need to be added to the solver manually; see e.g. [here](https://github.com/JuliaOpt/MathOptInterfaceSCS.jl/blob/52e6a65876f98deeb9680199bfccae305d2825a0/src/MathOptInterfaceSCS.jl#L31-L36), but this will change.

In the future, I would imagine that one could define a new constraint and a new bridge and give both to JuMP which would pass it along to the [InstanceManager](https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/issues/32).
The InstanceManager (or something new like AutomaticBridger) would have a list of bridges. When an instance does not support a constraint that is added, it will look through its bridges to see which one provides an appropriate transformation and then add the appropriate bridge to the instance.
The InstanceManager could create one AutomaticBridger for the standalone instance (here the transformation does not need to be applied since it is not a solver instance, the bridge will simply allow to store the new type of constraints in a type stable way) and one for the solver (here the transformation will play a key role). This would resolve this issue as the new constraints will be stored in the bridge in a type stable way.

**Comment by mlubin** [comment]
@blegat, could you clarify how an AutomaticBridger resolves this issue? Don't you still have to list all possible sets to be stored/bridged ahead of time?

**Comment by blegat** [comment]
The extension (here ConditionalJuMP) is responsible to call the macro creating the specialized code for this constraint. In this case, this would give something like
```julia
# Inside ConditionalJuMP
struct Complementarity <: AbstractSet
...
end
struct ComplementarityBigMBridge <: AbstractBridge
...
end
# The bridge will call MOIU.@bridge which creates the specialized container
@bridge ComplementarityBigM ComplementarityBigMBridge () (Complementarity,) () () () () () (VectorAffineFunction,)
JuMP.addcustombridge(ComplementarityBigMBridge, ComplementarityBigM)
```

**Comment by mlubin** [comment]
How does `JuMP.addcustombridge` handle the changing the internal instance type used so that it can support the new `Complementarity` set?

**Comment by blegat** [comment]
It is passed to the automatic bridger, e.g.
```julia
function addcustombridge(instancemanager::InstanceManager, bridgeinstance::AbstractBridgeInstance, bridge::AbstractBridge)
    addbridge!(instancemanager.automaticbridger, bridgeinstance, bridge)
end
```
Then when needed, the automatic bridger do something like
```julia
automaticbridger.instance = bridgeinstance(automaticbridger.instance)
```

**Comment by mlubin** [comment]
@blegat, it would be useful to have an independent solution to this issue that's not tied into the bridge infrastructure. JuMP would be more flexible if it uses an implementation of `AbstractStandaloneInstance` that doesn't require the list of possible sets and functions to be defined at compile time. The only reason for not doing so is performance, and we haven't evaluated the performance trade-off yet.

**Comment by blegat** [comment]
Using the bridges on top of the standalone instance may indeed be overkill. As mentioned [here](https://github.com/JuliaOpt/JuMP.jl/issues/1152#issuecomment-354373234), for a standalone instance, the transformation part of the bridge mechanism is useless.
We could create a container in the `MOIU.@instance` that stores arbitrary function/set pairs although it might be cleaner to have a structure that sits on top of a standalone instance and in case `canaddconstraint` returns false for the underlying instance, it stores the constraints it its container (a bit like what is currently done with the bridges but without transformation and without the need to have a specialized container). When the instance is queried, it mixes both the constrained stored inside the underlying instance and the constraints stored inside the universal container in a transparent way.

**Comment by mlubin** [comment]
> it might be cleaner to have a structure that sits on top of a standalone instance

I don't necessarily view this as cleaner. If we can make a standalone instance that stores arbitrary functions and sets without compromising performance, then we should do so. Wrappers add extra levels of complexity.

**Comment by blegat** [comment]
It seems to me that adding arbitrary constraints to the `MOIU.@instance` will increase the size of a code that is not decoupled which makes it more complex. Moreover, it adds complexity to the definition of `MOIU.@instance`. Instead of doing one thing, it now tries to do 2 different things. Some user of the MOIU.@instance only need the first of the 2 things when using `MOIU.@instance`, e.g. users of InstanceManager that are not JuMP and don't care about arbitrary constraints and the `MOIU.@bridge` macro.
One way to nicely decouple the two tasks (a standalone instance with specialized code and a standalone instance supporting arbitrary constraints) could be to keep the `MOI.@instance` as is and create a new standalone instance type which supports any constraint and do no do need any macro.
Then we could create a structure that compose two instances with the same variables and concatenate the constraints in both. It is maybe not a good idea though since it cannot enforce variables indices to be the same and having a mapping might make it inefficient so it's just a though ^^

**Comment by mlubin** [comment]
I was definitely thinking that the implementation of this new standalone instance would be separate from the current MOIU.Instance.

**Comment by mlubin** [comment]
@rdeits, the type-erased container does surprisingly well in your benchmarks. Maybe it would be worth throwing together an `AbstractStandaloneInstance` implementation based on that ideal to have as a baseline.

**Comment by rdeits** [comment]
Yeah, I was surprised at how quick adding things to the container was, but I'm pretty concerned about how fast actually using those constraints (by iterating over the collection) will be. I'll try benchmarking that as well.

**Comment by blegat** [comment]
One method that might be slow is getting [`ListOfConstraintIndices{F, S}`](http://www.juliaopt.org/MathOptInterface.jl/latest/apireference.html#MathOptInterface.ListOfConstraintIndices) with ErasedConstainer since the constraints are all mixed together.

**Comment by rdeits** [comment]
Good point. I'm currently building Julia from source since the performance characteristics have changed a lot since 0.6 already.

**Comment by rdeits** [comment]
This has turned up an interesting performance regression in Julia itself: https://github.com/JuliaLang/julia/issues/25359

**Comment by rdeits** [comment]
I've added a dummy `build_constraint()` function to test iterating over the constraints: https://github.com/rdeits/jump-containers/commit/9a1f3a691802799541ddb84bda89d02c7e596adf#diff-ff9ce2a496a2f898a3f7ddbf7a70af32R28

Some initial benchmarking does show that the type-erased container is indeed the slowest. Notably, there's almost no measurable overhead when iterating over the constraints using any of the dict-of-vectors approaches:

```
container = SpecializedContainer
Adding constraints: 	  2.474 μs (55 allocations: 7.34 KiB)
Iterating over constraints: 	  5.784 μs (123 allocations: 13.08 KiB)
container = TypeContainer
Adding constraints: 	  8.984 μs (59 allocations: 7.66 KiB)
Iterating over constraints: 	  6.031 μs (123 allocations: 13.08 KiB)
container = IDContainer
Adding constraints: 	  7.986 μs (70 allocations: 8.00 KiB)
Iterating over constraints: 	  6.021 μs (123 allocations: 13.08 KiB)
container = IDVectContainer
Adding constraints: 	  5.669 μs (61 allocations: 7.78 KiB)
Iterating over constraints: 	  6.189 μs (123 allocations: 13.08 KiB)
container = ErasedContainer
Adding constraints: 	  2.839 μs (154 allocations: 8.19 KiB)
Iterating over constraints: 	  8.189 μs (123 allocations: 13.08 KiB)
```

**Comment by mlubin** [comment]
@rdeits, thanks for running these benchmarks. Either `IDContainer` or `IDVectContainer` seems appropriate. `IDContainer` is more appealing since the layout is a bit simpler. The vector optimization could be implemented as its own standalone data structure (an alternative implementation of `Dict`), right?
