### ISSUE TITLE
Inconsistent type when calling @variable

### ISSUE THREAD

**Issue by fa-bien** [JuliaOpt/JuMP.jl#1463]
The two following expressions have different values:
```julia
julia> typeof( @variable(Model(), [1:3]) )
Array{JuMP.Variable,1}

julia> typeof( @variable(Model(), [2:3]) )
JuMP.JuMPArray{JuMP.Variable,1,Tuple{UnitRange{Int64}}}
```
I find this inelegant but I'm relatively new to Julia -- so maybe I don't understand Julia culture well enough. I would expect both calls of the `@variable` macro with parameters of the same type to return values of the same type, since both are collections of variables anyway. A bit more context: I would like to have a mutable struct that includes a collection of variables, and to be able to specify the type of that collection regardless of range bounds; at the moment I cannot do that.

(odow: formatting update)

**Comment by odow** [comment]
Hi @fa-bien, 

Welcome to JuMP!

> I would expect both calls of the `@variable` macro with parameters of the same type to return values of the same type, since both are collections of variables anyway.

This is not true even of functions.
```julia
function foo(x::Int)
    if x == 0
        return "x is zero"
    else
        return 2 * x
    end
end

foo(0) == "x is zero"
foo(1) == 2
```
Macros are even less consistent since they re-write code based on the input expression. In your case, the macro infers that your set is a 1-based range, and so returns an array instead of a JuMP array. You can work around this as follows:
```julia
model = Model()
indices = 1:3
@variable(model, x[indices])  # the macro cannot infer the value (or type) of `indices`
typeof(x)  # JuMPArray
```

In the future, you should post usage questions like this to our [discourse forum](https://discourse.julialang.org/c/domain/opt). There are more readers who might answer your question, and it helps other people who might have this question in the future.

**Comment by mlubin** [comment]
See slides 34 and 35 of http://www.juliaopt.org/meetings/bordeaux2018/lubin.pdf for a review of types produced by `@variable` given different index sets in JuMP 0.19 (not yet released). You may be interested in the `container=` keyword if you want containers of a consistent type.

**Comment by odow** [comment]
Closing because we now have documentation describing the various return types and how to use the `container` keyword: http://www.juliaopt.org/JuMP.jl/dev/variables/#Variable-containers-1

Please re-open if the documentation isn't clear.
