### ISSUE TITLE
[Build Failure]: Unable to build with Julia v1.0.0

### ISSUE THREAD

**Issue by rowhit** [JuliaOpt/JuMP.jl#1503]
I am not sure if duplicate item. However the Julia 1.0.0 is not able to install this package.

**Comment by blegat** [comment]
See https://discourse.julialang.org/t/jump-and-julia-0-7-1-0/12964
Note since we write this post, @ExpandingMan has helped getting the branch release-0.18 working on Julia v1.0 but we are currently blocked by a segfault in Julia v0.6: https://github.com/JuliaOpt/JuMP.jl/issues/1501.
In any case, you can try either the branch release-0.18 or the branch master and they should both work on Julia v1.0
