### ISSUE TITLE
Feature request: get all variables in the model

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1612]
```julia
function all_variables(model::Model)
    return [Variable(model, idx) for idx in MOI.get(model, MOI.ListOfVariableIndices())]
end
```

**Comment by blegat** [comment]
I know that this is an additional dependency but we might consider doing
```julia
function all_variables(model::Model)
    mappedarray(idx -> Variable(model, idx), MOI.get(model, MOI.ListOfVariableIndices())
end
```
This avoid allocation of the resulting vector, the user can still do `collect(all_variables(model))` if he wants a `Vector` but most of the time, he just need to iterate over it so allocating the array is inefficient.

We might also need such lazy map of arrays to implement [`lazy_operate`](https://github.com/JuliaOpt/MathOptInterface.jl/issues/526) so we'll have to choose whether we accept [MappedArrays](https://github.com/JuliaArrays/MappedArrays.jl) as a dependency or add our own implementation in MOI.
Note that the package is only one file of 250 lines and is inside the JuliaArrays organization so it should be quite easy to maintain. The fact that it is so short also makes it easy to replicate in MOI but it might be time consuming to maintain it (it is rather performance critical so we'll have to benchmark it precisely and track down regressions).

**Comment by mlubin** [comment]
I think this should be present in 0.19 because it's needed to reproduce the previous functionality of using results as starting points, e.g.,
```julia
vars = JuMP.all_variables(model)
JuMP.set_start_value.(vars, JuMP.value.(vars))
```

**Comment by mlubin** [comment]
I agree that a lazy version could be nice, but don't really see the case where the call to `all_variables` would be a bottleneck that it's worth importing a new dependency just to address. We would also have to rethink anywhere that we return an array and come up with a convention on when to be lazy.

**Comment by blegat** [comment]
I have found myself needed this features a few times in order to construct a MockOptimizer. I agree that the optimization should come later.
As for the mapped array, having one in MOI would be simpler than the one in MappedArrays.jl as it will only be for Vector and not arbitrary sized array and we could make it more efficient by requiring to be also provided with the return type so that it it's `eltype` is not `Any` which would make it more efficient (and make the bridges truly allocation free), but that's off topic :)
