### ISSUE TITLE
SDP doesnt solve using MOSEK, throws error "no method matching : setindex_shape_check(::Int64, ::Int64)"

### ISSUE THREAD

**Issue by taranjitsinghb** [JuliaOpt/JuMP.jl#1660]
This is a sample example of an SDP optimization problem. The JuMP parses amazingly to solve it with SCS and CSDP solvers (and I hank you all for that). However, I noticed that these solvers fail to solve larger systems (restarts Julia), which eventually I will using to solve linear control problems. My ultimate idea is to use Pajarito fro MISDP problems.  
However, I believe that MOSEK should be able to solve these large problems, but when I use it, it throws an error which is attached in the zip files. 

Thank You. 

[test_sdp_jump.zip](https://github.com/JuliaOpt/JuMP.jl/files/2645155/test_sdp_jump.zip)

**Comment by odow** [comment]
Hi @taranjitsinghb

This looks like a bug in MOSEK rather than JuMP. You should close this issue and open a new issue in that repo https://github.com/JuliaOpt/Mosek.jl

In addition, no need to upload the files as a .zip. You can paste formatted code into Github by surrounding it in triple back-ticks like so
```
    ```julia
    foo(x) = 2x
    ``` 
```

**Comment by taranjitsinghb** [comment]
Thank you so much. I will do that.
