### ISSUE TITLE
no method matching for "getsimplexiter(::Model)"

### ISSUE THREAD

**Issue by stefanobenati** [JuliaOpt/JuMP.jl#1821]
Hi, 

I have a maximization problem with a huge number of variables.
I have two linear programming (LP) formulations that I want to compare.
Therefore I wish to know the number of iteration the LP solver uses to calculate the optimum.
Apparently it is not difficult, using instruction

getsimplexiter(m)

documented in JuMP:

http://www.juliaopt.org/JuMP.jl/0.18/refmodel.html

Unfortunately, I get an error message, as if the command were not recognized.

To replicate the error, here is a small code:

```julia
using JuMP, Gurobi, MathProgBase

m = Model(solver = GurobiSolver(OutputFlag = 1))
@variable(m, 0 <= x <= 2)
@variable(m, 0 <= y <= 30)

@objective(m, Max, 5x + 3y)
@constraint(m, 1x + 5y <= 3.0)

status = solve(m)
t1 = getsolvetime(m)
it = getsimplexiter(m)

println("Objective value: ", getobjectivevalue(m))
println("x = ", getvalue(x))
println("y = ", getvalue(y))
println("Time = $t1")
println("Iteration = $it")
```

The error message is:
```
MethodError: no method matching getsimplexiter(::Gurobi.GurobiMathProgModel)
```

I am using:
Julia 	1.0.3
JuMP 	0.18.5
Gurobi 	0.5.8
MathProgBase 0.7.7

Any suggestion? I will be greatly grateful!

Edit(odow): formatting.

**Comment by odow** [comment]
Hi @stefanobenati, 

Unfortunately, some solvers do not implement the full API defined by JuMP. Gurobi and `getsimplexiter` is is one example.

Since this is Gurobi specific, I've opened in that repository: https://github.com/JuliaOpt/Gurobi.jl/issues/190

I'll close this issue, so let's take the future discussion over there and I can show you how to implement it.
