### ISSUE TITLE
Binary variable inconsistency

### ISSUE THREAD

**Issue by ohmsweetohm1** [JuliaOpt/JuMP.jl#2081]
I feel the following syntax is inconsistent

```julia
using JuMP
model = Model()
@variable(model, x, Bin)
@variable(model, 0<=y<=1, Bin)
@variable(model, -2<=z<=2, Bin)
```
A binary variable should have the inherent bounds 0 and 1.
`lower_bound(x)`
> ERROR: Variable x does not have a lower bound.

How is it possible to have a binary variable with an upper bound of 2?
`(is_binary(z), upper_bound(z))`
> (true, 2.0)

It seems that the bounds are ignored internally. 
Thus the question arises: _Why allow bounds on binary variables?_

**Comment by mlubin** [comment]
The concepts behind constraints in JuMP are explained here: http://www.juliaopt.org/MathOptInterface.jl/stable/apimanual/. Please have a look and let us know if you find inconsistencies.

Constraints are intersected. It's up to solvers to find solutions that respect the constraints. Obviously a binary variable cannot take a value of two, so the upper bound is redundant in that case. JuMP doesn't prevent you from writing redundant constraints. This is consistent with allowing you to write:
```julia
@variable(model, x, Bin)
@constraint(model, x <= 2)
```

> It seems that the bounds are ignored internally.

Do you have any evidence of a solver ignoring bounds?

> Why allow bounds on binary variables?

Almost all solvers do. It's also valid to set the upper bound of a binary variable to zero. in order to force the variable to zero.

**Comment by mlubin** [comment]
Closing as there's no actionable item. Feel free to continue the discussion at https://gitter.im/JuliaOpt/JuMP-dev or https://discourse.julialang.org/c/domain/opt.
