### ISSUE TITLE
Question: how does JuMP compare with OpenMDAO

### ISSUE THREAD

**Issue by mantielero** [JuliaOpt/JuMP.jl#2153]
Do they fill the same niche?

**Comment by mlubin** [comment]
This is not a bug report or feature request for JuMP, so https://discourse.julialang.org/c/domain/opt would be a better place for this discussion. I'm hesitant to say much because I've never seen OpenMDAO before; I'd rather answer a more specific question about "does JuMP do X?" and let you formulate an opinion on how they fill the niche you care about. JuMP fills a lot of niches beyond nonlinear optimization.

In any case, after a very brief look it looks like OpenMDAO does not implement [automatic differentiation](https://en.wikipedia.org/wiki/Automatic_differentiation) as JuMP does; instead, the only options are finite differences or hand-written derivatives:

http://openmdao.org/twodocs/versions/latest/basic_guide/first_mdao.html

> We’re using finite difference here for simplicity, but for larger models, finite differencing results in a high computational cost, and can have limited accuracy. It’s much better to use analytic derivatives with your models. You can learn more about that in the Advanced User Guide.

**Comment by mantielero** [comment]
Thanks closing it. I missed the discourse link. Sorry.
