### ISSUE TITLE
New way of setvalue

### ISSUE THREAD

**Issue by hect1995** [JuliaOpt/JuMP.jl#2154]
I am updating some JUlia v.0.6.0 code into 1.0+ and I receive the error:
`ERROR: MethodError: no method matching setvalue(::Array{VariableRef,2}, ::Array{Float64,2})`
When initializing the variables that I want to optimize as:
```
@variable(m, l1[1:sum(vOb),1:(N+1)])	# dual multiplier associated with obstacleShape
setvalue(l1,l1WS')
```
How should be translated now?

**Comment by odow** [comment]
You're looking for https://www.juliaopt.org/JuMP.jl/stable/variables/#Start-values-1.

```Julia
model = Model()
@variable(model, x[1:4])
set_start_value.(x, [1.0, 2.0, 3.0, 4.0])
```
Note how we use the broadcast `set_start_value.(` instead of `set_start_value(` to apply the function to each element of the vector.

You can also go
```Julia
model = Model()
@variable(model, x[i = 1:4], start = i)
```

p.s. Please post usage questions like this on the Discourse forum in future: https://discourse.julialang.org/c/domain/opt/13

**Comment by odow** [comment]
Closing since this is not an issue with JuMP. Please open a post on Discourse if you have any other difficulties porting the code to 1.0.
