### ISSUE TITLE
Missing promote operation

### ISSUE THREAD

**Issue by ohmsweetohm1** [JuliaOpt/JuMP.jl#2213]
```julia
using JuMP

X, b = rand(10,3), rand(3,1)
y = X * b

m = Model()

b_ref = @variable(m, [1:3])
expr = @expression(m, y - X * b_ref)
```
 
> ERROR: `promote_operation(-, Array{Float64,2}, Array{JuMP.GenericAffExpr{Float64,JuMP.VariableRef},1})` not implemented yet, please report this.

**Comment by odow** [comment]
Please provide a minimal working example that demonstrates the problem.

**Comment by odow** [comment]
Oh, I apologise. You do have a MWE, which I should have copy-pasted. 

The issue is that `y` is `Array{T, 2}`, and `X * b_ref` is `Array{T, 1}`. 

This isn't expected to work because it doesn't work for any Julia types. 

You either need to use `@expression(model, y .- X * b_ref)`, or use `b = rand(3)` and not `b = rand(3, 1)`.
