### ISSUE TITLE
CPLEX test failure

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#365]
```julia
[callback] Test heuristics
     - With solver GurobiSolver
     - With solver CplexSolver
  Failure   :: (line:-1) :: With solver CplexSolver :: got 3.0
    getValue(x) => roughly(1.0,1.0e-6)
  Failure   :: (line:-1) :: With solver CplexSolver :: got 5.0
    getValue(y) => roughly(2.0,1.0e-6)
```
Looks like it's accepting the infeasible solution.
Has CPLEX behavior changed in 12.6.1?

**Comment by joehuchette** [comment]
Ahh, Juan Pablo ran into cases where CPLEX rejects feasible solutions, so I committed https://github.com/JuliaOpt/CPLEX.jl/commit/ff26ae3c7ba211f4c82dcab408a0cec97d81b11e which fixed the issue. Not sure what we want to be doing in general, but it doesn't seem unreasonable to expect users to know that their solution is feasible before adding it.

**Comment by mlubin** [comment]
Could we distill this down to a reproducible example?
It seems like a basic user friendliness issue. I'm worried that if we don't check feasibility of solutions, we'll get a stream of mysterious bug reports about it.

**Comment by joehuchette** [comment]
I think it was an MIQCP example, cc @juan-pablo-vielma. I'm not sure if it's a worse w.r.t. usability to have the solver reject solutions for (possibly spurious) infeasibility concerns or to accept infeasible solutions the user accidentally passed in. At least the first is transparent as to what it's doing---if you give the solver a solution, it'll use it.

**Comment by juan-pablo-vielma** [comment]
It is a weird numerical problem with the LiftedLP algorithm, not sure how to reproduce it on its own. I had the same problem with CPLEX's C++ interphase. The solution there was to fix all variables on the node LP to the target solution and solve the node LP. Then CPLEX would accept the solution. Can JuMP solve the node LP in heuristic callback? Another option is to add the check as an optional parameter to addSolution()

**Comment by joehuchette** [comment]
FWIW I also had Gurobi <6.0.0 reject the optimal solution for the [bnatt350 example](https://github.com/JuliaOpt/JuMP.jl/blob/master/examples/bnatt350.jl), which is weird because it's a 0/1 problem. This kind of finicky behavior in both solvers makes me more inclined to trust the user over the solver.

It would probably make sense to solve the node LP at the CPLEX.jl level instead, but that sounds like an awful lot of complexity. @IainNZ what are your thoughts on heuristic callback and infeasible solutions?

**Comment by mlubin** [comment]
Not checking feasibility of the user-provided solution can result in the solver giving the plain wrong answer while returning ``:Optimal`` status, which should be somewhat terrifying. I think adding an option (which defaults to checking feasibility) is a good compromise.

**Comment by IainNZ** [comment]
I've had Gurobi reject solutions that I'm pretty sure are feasible, its frustrating. I think an option that verifies the solution is feasible is neat, but I don't feel like it should be on by default, because then you are getting slow performance for unexpected reasons.

**Comment by mlubin** [comment]
I dunno, I'd say that slow performance for unexpected reasons is preferable to incorrect answers for unexpected reasons.

**Comment by joehuchette** [comment]
Well, I mean modeling your problem incorrectly can also give a plain wrong result with the ``:Optimal`` status; I'm not sure it's unreasonable to expect that information the user gives us explicitly is correct for the problem they want to solve. We don't verify that user cuts are valid, for instance (nor should we).

In principle I agree the option is a good compromise, but I worry about having it on by default, since it can be really hard to figure out whether the solver is actually taking your solution or not.

**Comment by juan-pablo-vielma** [comment]
And GLPK does not check the solutions, so checking by default would not be consistent among different solvers.

**Comment by mlubin** [comment]
GLPK does check the solutions: https://github.com/JuliaOpt/GLPKMathProgInterface.jl/commit/04fa677bafa2072016fa6d329d419c1153ffc251

**Comment by mlubin** [comment]
We added these tests because CPLEX was accepting a partial solution that wasn't even feasible (https://github.com/JuliaOpt/JuMP.jl/pull/248). If we can deal with the issue of partial solutions then I'm okay with not checking feasibility of full solutions.

**Comment by juan-pablo-vielma** [comment]
Then the manual needs updating it says
> For example: GLPK will not check the feasibility of your heuristic solution.

**Comment by mlubin** [comment]
If you comment out lines
```
        setSolutionValue!(cb, x, 3)
        setSolutionValue!(cb, y, 5)
        addSolution(cb)
```
from the heuristics test, just leaving
```
        setSolutionValue!(cb, x, 3)
        addSolution(cb)
```
CPLEX still fails the test and gives a solution with ``x = 3`` which is infeasible. That's just junk to me, if you don't provide a complete solution and the solver can't find a feasible completion, it should be ignored.

**Comment by juan-pablo-vielma** [comment]
what value of y does CPLEX return?

**Comment by joehuchette** [comment]
It's junk you gave it, though. I'm also wary of checking feasibility on the JuMP side because verifying it with ``getconstrmatrix`` like in the GLPK interface doesn't imply the solver will actually accept it (the bnatt350 example was like this). 

I'm just not sure how solver independent we can get here, because the solvers behave differently for really opaque reasons.

**Comment by juan-pablo-vielma** [comment]
Actually, if performance was not an issue, the check should be at the JuMP or MathProgBase level for all solvers, without allowing the solver to do its own check. This would guarantee consistent behavior  among all solvers.

**Comment by mlubin** [comment]
CPLEX returns y = 2, which satisfies the variable bounds on y but violates ``x + y <= 3.5``.

We can't really check feasibility at the JuMP level because JuMP has no concept of feasibility tolerances.

@joehuchette sure it's junk but I can imagine that a reasonable person may want to implement a heuristic that rounds a few variables and lets the solver try to complete the solution. As it is now, you can't implement this safely. What about turning feasibility checking on in CPLEX.jl for incomplete solutions and leaving it off for complete solutions?

**Comment by mlubin** [comment]
Note that CPLEX even gives the wrong answer when you pass in ``x = 2``, which respects the variable bounds on ``x``. The worst part is that there *is* a feasible solution with ``x = 2``, but CPLEX chooses an infeasible one. So this is just plain broken and unusable as it is.

**Comment by joehuchette** [comment]
I changed the behavior so that it checks feasibility iff the solution is only partially available; I think this is a good compromise. I'm still a bit unhappy with the inconsistency between solvers w.r.t. _complete infeasible_ solutions (e.g. Gurobi checks them itself, CPLEX doesn't), but I'm not sure what all we can do to make this solver independent.

**Comment by mlubin** [comment]
Okay, I think we can consider this resolved until the next user complaint.
