### ISSUE TITLE
Add a way to access variable values via the model object

### ISSUE THREAD

**Issue by davidanthoff** [JuliaOpt/JuMP.jl#399]
It would be handy if something like this would work:
````
function getmodel()
  m = Model()
  @addVar(m, x)
  [...]
  return m
end

model = getmodel()
solve(model)
getValues(m, :x)
````
or maybe even
````
m[:x]
````
In any case, the core problem to solve is that variables of the problem might be defined in a function, but I might want to get at their value somewhere else in the code where those variables are out-of-scope, but where I passed a model object.

**Comment by mlubin** [comment]
We usually suggest to structure the code so that the variables remain in scope, e.g., ``model, x = getmodel()``. It wouldn't be hard to add a dictionary to JuMP models, my only worry is what it would mean to define two sets of variables named ``x``. Right now (except for printing models), the names of variables have no special meaning and we just follow Julia's scoping rules. Admittedly this sometimes leads to behavior that's unintuitive coming from AMPL/GAMS.

**Comment by IainNZ** [comment]
I agree with @mlubin in that this is a philosophical-type thing mainly, with a technical element too. We try to embrace that we are in a "serious" programming language, so try to avoid that type of logic and instead rely on Julia features like multiple returns/scope rules/closures.

**Comment by joehuchette** [comment]
Personally I think that field overloading so that, e.g. ``m.x`` worked as you would expect would be really cool.

**Comment by davidanthoff** [comment]
Here are some specific use cases where this would be super handy:
- Write a little helper function that takes a JuMP model and writes out all the variable values into a file for further analysis
- Write a helper function that stores all optimal values from a solved JuMP model, stores them somewhere, and then later allows me to set the initial values of a JuMP model to these stored values
- Write a UI package that explores a solved JuMP model. This is not something I intend to do ;), but I could easily see this a being very handy
Generally, I find that for almost all non-trivial code we write we like to separate model construction into a different function from model result evaluation. Right now we pass the JuMP variables via return statements etc., but boy is that a lot of boilerplate code that seems entirely unnecessary (and of course that is the kind of code where bugs slip in...)

Maybe another way to look at this is whether there are any real downsides? Performance wise this shouldn't matter, and if one doesn't want to use it, this would be completely optional, right?

**Comment by IainNZ** [comment]
For the first use case, I guess I'd do something like

```julia
type MyProblem
  model
  x
  y
end

function createproblem()
  m = Model()
  @defVar(m, x[1:10)
  @defVar(m, y[1:100], Bin)
  #...
  return MyProblem(m, x, y)
end

p = createproblem()
solve(p.model)
getValue(p.x)
```

because thats completely unambiguous and avoids any issues with duplicate variable names.
I guess that also works for the second, in fact I have this exact same use case in my research code and I use types to store it.

As for the model exploration, that would benefit from some generic way to iteratre over variable groups, but like you say, no ones in a rush to do it.

Downside is complexity and code maintenance, IMO, and general desire to only add complexity where it isn't provided by Julia.

**Comment by mlubin** [comment]
> - Write a little helper function that takes a JuMP model and writes out all the variable values into a file for further analysis
> - Write a helper function that stores all optimal values from a solved JuMP model, stores them somewhere, and then later allows me to set the initial values of a JuMP model to these stored values

Well, if the model is *identical* all you need to do is save and restore the ``m.colVal`` array using, e.g., the [JLD](https://github.com/timholy/HDF5.jl) format. As Iain mentioned, we don't want to get into the business of adding features to JuMP which can easily be accomplished with Julia code.

What we *could* do is just keep a dictionary of variable names that you can look up later. Something like
```
@defVar(m, x[1:N])
getVar(m, :x) # another name for x
```
This would be off by default to avoid any unnecessary runtime overhead. Maybe it would just be an error to have multiple variables with the same name if this feature is enabled? I can see how this would be useful, and we shouldn't be paralyzed by the naming issue so long as the feature is designed in a way that can be tweaked later without breaking code (e.g., by using a method ``getVar(m,:x)`` instead of ``m.vars[:x]``).

**Comment by davidanthoff** [comment]
@IainNZ That is the kind of pattern we use. It is really hard to maintain once you have a mid-size model. We have something like ~30 names variables, so for each one we now need to keep the type definition, the ``defVar`` line and the constructor call in the return statement in sync. It works, but especially in the phase where we experiment around with the model, try to debug things etc. it is a pain and cumbersome.

@mlubin Yes, ``getVar(m, :x)`` would completely solve this. With ``getVar`` in place it would also be trivial to define a ``getValues(m, :x)``, right?
Throwing an error if one tries to add a var with a name that already exists in the model seems entirely reasonable to me. Actually, when I construct a model in IJulia, and then eval the model object, I get a nice display of the variables in the model already, including their names. Right now there can be vars with the same name, which I find a bit odd, maybe that should just generally be a bug?

**Comment by mlubin** [comment]
We need to allow variables with duplicate names because model generation could be pluggable and modular where different modules don't know about the names in other modules (see #298). The solution to this might be to introduce some sort of namespaces for variables, but we'll definitely put that off until it becomes an issue.

I'm okay with ``getVar(m, :x)``, @IainNZ, @joehuchette?

**Comment by joehuchette** [comment]
That's fine with me, sounds like a good addition. Still think ``m.x`` as sugar for that would be neat, though (when it's possible with field overloading).

**Comment by mlubin** [comment]
Sure, but that doesn't exist yet, maybe before I graduate :)

**Comment by IainNZ** [comment]
`m(:x)` as an alias for `getVar(m, :x)`? :D

**Comment by joehuchette** [comment]
I think ``m[:x]`` is a little less magical (but only a _little_).

**Comment by mlubin** [comment]
Eh

**Comment by IainNZ** [comment]
One day I'll find the perfect use for call overloading, and it will be magical.

**Comment by IssamT** [comment]
I'm reopening this thread just to share an alternative solution that I use which might be useful to other JuMP users. It doesn't handle some cases like anonymous variables but could be adjusted to do so... It is useful not only to process the solution but also if you want to have different functions building your model, or having independent functions for callbacks...

The following function defines julia variables which point on model variables and constraints.

```julia
function generatemodelhandlers(m::Model)
    code = :()
    for k in keys(m.varDict)
        code = quote
            $code
            $(k) = $(m.varDict[k])
        end
    end
    for k in keys(m.conDict)
        code = quote
            $code
            $(k) = $(m.conDict[k])
        end
    end
    eval(code)
end
```

Here is a usage example:

```julia
function createproblem()
    m = Model()
    @variable(m, x >= 0)
    @variable(m, y >= 0)
    @constraint(m, constr, x + y >= 3)
    @objective(m, Min, 2*x + y)
    return m
end

function procsolution(m::Model)
    generatemodelhandlers(m)

    @show getvalue(x)
    @show getvalue(y)
end

m = createproblem()
solve(m)
procsolution(m)
```

**Comment by mlubin** [comment]
@IssamT, that doesn't do what you think it does. ``eval`` creates variables in the global scope, they're not local to the function.

**Comment by IssamT** [comment]
Thanks @mlubin. You are right, I was mistaken about `Eval`

**Comment by IssamT** [comment]
So I guess the only little improvement we can hope for is using something similar to this macro, unless it's again not doing what I think it's doing lol.

```julia
macro generatemodelhandlers(m, args...)
    code = :()
    for arg in args
        tmp = "$arg"
        exp = :( $arg = getvariable($m, Symbol($tmp) ) )
        @show exp
        code = quote
            $code
            $exp
        end
    end
    @show code
    esc(code)
end
```

and use it like this

```julia
function procsolution(m::Model)
    @generatemodelhandlers(m, x, y, z)

    @show getvalue(x)
    @show getvalue(y)
    @show getvalue(z)
end
```
