### ISSUE TITLE
Ordering of coefficients and variables

### ISSUE THREAD

**Issue by odow** [JuliaOpt/JuMP.jl#448]
Is there a reason why only Coefficient times Variable (and not Variable times Coefficient) is supported when using macros?

For example `@setObjective(m, Min, x * 2)` results in the error 
`ERROR: Cannot construct an affine expression with a term of type (GenericAffExpr{Float64, Variable})*(Int64) in error at error.jl:21 (repeats 2 times)`

while `setObjective(m, :Min, x * 2)` works.

There is a small paragraph in the Quick start guide that states this, but it might be helpful (especially for new users - I had this problem myself when I first started using JuMP, and just saw someone else encounter it while writing their first JuMP model) to have a more explanatory error message.

**Comment by mlubin** [comment]
Yes, the reason was for performance because inside of macros we don't know types, and it was faster to assume that the coefficients were on the left. Variable*coefficient has been working well with JuMP on julia 0.4 since JuMP version 0.7. We recently went ahead and enabled it on 0.3 for user convenience even though there's a performance hit (on 0.3 only).

**Comment by tkelman** [comment]
> We recently went ahead and enabled it on 0.3 for user convenience even though there's a performance hit (on 0.3 only).

Didn't notice that, but that's good to hear. That was a complicated limitation to explain to people.

**Comment by odow** [comment]
My mistake. I was still on Julia 0.3.7. Cheers!
