### ISSUE TITLE
getValues in the usercut / Lazy/ Heuristic callbacks

### ISSUE THREAD

**Issue by kaarthiksundar** [JuliaOpt/JuMP.jl#450]
When using Callbacks, cplex offers a getValues function that can be used to obtain the solution values for an array of variables. This can reduce the number of function calls considerably when the MILP has a huge number of variables. It seems this function is not present in the documentation or the source code. Is this implemented?

**Comment by mlubin** [comment]
JuMP internally gets the solution vector with one call to CPLEX. There's no unusual overhead for using ``getValue`` many times inside of a callback. If you're worried about performance, call ``getValue`` on a single variable, e.g., ``getValue(x[i])`` instead of ``getValue(x)[i]`` since the latter requires a temporary allocation.
