### ISSUE TITLE
Do we need `5 >= x >= 1`

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#517]
We support `@defVar(m, 5 >= x >= 1)`, but I'm not sure we really should. I'd be in favour of just making it an error.

**Comment by joehuchette** [comment]
It is a bit inconsistent that
```
julia> @addConstraint(m, 5 >= x >= 1)
ERROR: in @addConstraint (5 >= x >= 1): only ranged rows of the form lb <= expr <= ub are supported.
```
doesn't work.

**Comment by mlubin** [comment]
I'm not a big fan of the syntax, but not sure if we need to break things now if this is how some people prefer to write down variable bounds.

**Comment by IainNZ** [comment]
I don't even think its documented, I think it was added in one of the `@defVar` refactors just because it was possible.

**Comment by mlubin** [comment]
@yeesian seems to use this syntax in his examples

**Comment by IainNZ** [comment]
Yeah but that guys crazy ;)

**Comment by mlubin** [comment]
We'd at least have to deprecate for a version cycle. The syntax is rough on the eyes but it's still clear and easy to understand. We don't have the corresponding syntax for two-sided constraints because variables with upper and lower bounds are much more common than two-sided constraints.
Here's the original commit: https://github.com/JuliaOpt/JuMP.jl/commit/a1d0c87265fe0f3b841aba8983fc2d33e15b774f

**Comment by yeesian** [comment]
> @yeesian seems to use this syntax in his examples

Oops, did I? I don't mind changing the examples (if any).

**Comment by yeesian** [comment]
Hah yeah, whoops, [caught in the act](https://github.com/JuliaOpt/KNITRO.jl/blob/master/examples/jump_minlp.jl), lol.
