### ISSUE TITLE
API for components and nodal equations

### ISSUE THREAD

**Issue by tshort** [JuliaOpt/JuMP.jl#647]
I've put together an example where a model can be defined by components. Each component is a function that can define JuMP variables and constraints. Components are plugged together by using common "nodes." These nodes can correspond to physical quantities. For electrical circuits, a node is a voltage reference. For heat transfer problems, a node is a temperature. This is how components are defined and connected in [Sims.jl](https://github.com/tshort/Sims.jl/). 

It's also easy to define submodels built from other components. With JuMP, this approach can be used to solve systems or for optimization. 

Here is an example of a JuMP model using this component-based formulation:

```julia
function model()   
    m = Model()
    v1 = 10.0       # a known voltage, a voltage source
    @defVar(m, v2)
    @defVar(m, v3)
    resistor(m, v1, v2, 3)
    resistor(m, v2,  0, 6)
    resistor(m, v2, v3, 3)
    resistor(m, v3,  0, 3)
    addnodalequations(m)   # fix up nodal equations
    m
end
```

Here is how `resistor` is defined:
```julia
function resistor(m::Model, n1, n2, R)
    i = localVar(m, string("resistor_I_", n1, "-", n2, "_"))
    branch(m, n1, n2, i)
    @addConstraint(m, n1 - n2 == i * R)
end
```

See the following for more complete examples for solving and optimization:

https://gist.github.com/tshort/b23e8fbe78c2c4e31591

This implementation is kludgey. `localVar` uses non-exported functions, and `addnodalequations` is a complete hack to collect node variables and sum flows into them.

Does anyone have any suggestions on API (existing or new) in JuMP that would allow something like this in a more straightforward fashion?

**Comment by IainNZ** [comment]
This is a lot to understand, so I'll have to visit it, but I will say that just because something isn't exported, doesn't mean its not OK to use. So calling the `JuMP.Variable` constructor directly is totally fine and we expect that (or we should).
Why is `JuMP.registervar(m, varname, x)` needed? Is that a printing thing @joehuchette ?
I wanted to make sure also that you knew variable names don't need to be unique - I saw the `gensym` there and I'm not sure what its for.

What is `refbranch`? I don't understand this part of the code (or how JuMP is involved) - it seems like you are trying to track some global state?

Finally, its never been documented (I think? @mlubin ) but JuMP has aspirations to be "extensible" - in fact, there is a field inside the Model type for storing extra information. This has only even been used by us core developers, for the JuMPeR.jl and JuMPChance.jl packages in particular. They both add significant domain-specific functionality on top of JuMP. Maybe a browse through the start of their source could provide inspiration.

**Comment by tshort** [comment]
You've helped a lot, @IainNZ!. I didn't know that names don't need to be unique. That was what the `gensym` was for. I put in `JuMP.registervar` because I was mimicking the output of `@defVar`.

`refbranch` registers that a branch is connected to a node and gives the branch flow into the node. Then when the model has been specified, `addnodalequations` adds constraints based on these: at each registered node, the sum of branch flows into the node is set to zero. I used a hacky global variable to hold this information. The field you mentioned sounds perfect for this. Thanks for the pointers to JuMPeR and JuMPChance. I'll take a look at those.

**Comment by mlubin** [comment]
``registervar`` is only needed if you want the variable to be accessible from ``getVar``. It shouldn't be used for local variables, which is why it's not exported or documented.

**Comment by tshort** [comment]
`m.ext` works well to clean up my code. Looks like I've got everything I need. Gist updated:

https://gist.github.com/tshort/b23e8fbe78c2c4e31591

Thanks everyone.
