### ISSUE TITLE
Iterable JuMPArray

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/JuMP.jl#833]
It would be nice if the JuMPArray was iterable for clean use in for loops.

**Comment by mlubin** [comment]
What do you want this to look like? JuMPArray is sort of more like a dictionary than an array. You can use ``keys`` to iterate through it (see https://github.com/JuliaOpt/JuMP.jl/issues/646).

**Comment by ccoffrin** [comment]
Aaa I see.  With a generic Julia Dict you can do this,

```
for (k,v) in dict
   println(k) #key
   println(v) #value
end
```
which can cover the case when you only need the key or the value as well as when you want both.  What do you think about adding support for that?

**Comment by mlubin** [comment]
The larger issue is the inconsistencies between ``Array{Variable}`` and ``JuMPArray{Variable}``, because sometimes it's a JuMP artifact which type is returned:
```
S = 1:3
x = @variable(m, [S]) # JuMPArray
y = @variable(m, [1:3]) # Julia Array
```
It's a bad idea to have different iteration syntax for ``x`` and ``y``, so I'd like to figure out a consistent global approach (including solving https://github.com/JuliaOpt/JuMP.jl/issues/646) before adding any new features that might be broken later.

**Comment by ccoffrin** [comment]
Agreed, this is a bigger issue.  My first impression is that JuMPArray is a more general data-structure so that could be the standard type to return.  Then you only need to define iteration over JuMPArrays and its always consistent.

As a side note, in my case I am using `getvariable(m, symbol)` and getting a JuMPArray.

**Comment by mlubin** [comment]
If you're indexing over anything other than a product of 1-based ranges, then you won't get a plain Julia array.
