### ISSUE TITLE
max of array columns/rows

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaOpt/JuMP.jl#859]
Is it possible to compute max of array columns/rows withing @JuMP.NLobjective()

for example, something like

```
sum{maximum(a, 2)[i], i=1:n}
```

**Comment by mlubin** [comment]
JuMP does not currently support any sort of vector operations in nonlinear expressions, so no. If you're minimizing a maximum you should use the standard reformulation by introducing an extra variable that is element-wise greater than each term. Otherwise you can use ``ifelse`` to encode ``max``, may need to generate the expression [programmatically](http://www.juliaopt.org/JuMP.jl/0.14/nlp.html#raw-expression-input) if the dimension of ``a`` is a parameter.
