### ISSUE TITLE
How to check memory usage

### ISSUE THREAD

**Issue by mes9** [JuliaOpt/JuMP.jl#873]
I'm experimenting with my model on JuMP using the IPOPT solver, and I want to know if my changes  are helping or hurting the memory consumption. I have been using the @time solve(m)  to see the memory usage, but I do not know if that is the best method.

I also switched to the limited-memory hessian approximation and did not see any reduction in memory size with the @time macro, which surprised me. My problem is large, so memory is an issue

**Comment by mlubin** [comment]
I don't think Julia's ``@time`` macro accounts for memory allocated by IPOPT. You should direct your question to the IPOPT support list, since this isn't really a JuMP issue unless you can point to excess memory consumption by JuMP itself. You could also post your model to the julia-opt list to see if anyone has tips for reformulating it.

**Comment by mes9** [comment]
At what point does JuMP generate the 2nd derivatives? 

The problem size looks very similar when I ask JuMP to use AD to generate the 2nd derivatives versus the IPOPT option to use a limited-memory hessian approximation (Quasi-Newton Approximation of Second Derivatives). I am wondering if JuMP still generates the 2nd derivatives with AD but does not use them when I tell IPOPT to use the approximation.

**Comment by mlubin** [comment]
The Ipopt interface currently always asks JuMP for 2nd derivatives regardless of user options: https://github.com/JuliaOpt/Ipopt.jl/blob/41b1e7010a2ed92e1f21cec7df6195b581d5707a/src/IpoptSolverInterface.jl#L40
You may try experimenting with this.
