### ISSUE TITLE
 no method matching mapcontainer_warn(::JuMP.#_getValue, ::JuMP.JuMPArray{JuMP.NonlinearExpression,1,Tuple{UnitRange{Int64}}})

### ISSUE THREAD

**Issue by chkwon** [JuliaOpt/JuMP.jl#964]
```julia
using JuMP
M = [0  0 -1 -1 ;
     0  0  1 -2 ;
     1 -1  2 -2 ;
     1  2 -2  4 ]

q = [2; 2; -2; -6]

lb = zeros(4)
ub = Inf*ones(4)

items = 1:4
m = Model()
@variable(m, lb[i] <= x[i in items] <= ub[i])
@NLexpression(m, F[i in items], sum(M[i,j]*x[j] for j in items) + q[i])
@objective(m, Min, 1)
solve(m)

getvalue(x) # this works
getvalue(F[1]) # this works
getvalue(F) # this does NOT work
```

produces an error:

```julia
ERROR: MethodError: no method matching mapcontainer_warn(::JuMP.#_getValue, ::JuMP.JuMPArray{JuMP.NonlinearExpression,1,Tuple{UnitRange{Int64}}})
Closest candidates are:
  mapcontainer_warn(::Any, ::JuMP.JuMPContainer{JuMP.Variable,N}) at /Users/chkwon/.julia/v0.5/JuMP/src/JuMP.jl:824
 in _map(::Function, ::JuMP.JuMPArray{JuMP.NonlinearExpression,1,Tuple{UnitRange{Int64}}}) at /Users/chkwon/.julia/v0.5/JuMP/src/JuMPContainer.jl:150
 in getvalue(::JuMP.JuMPArray{JuMP.NonlinearExpression,1,Tuple{UnitRange{Int64}}}) at /Users/chkwon/.julia/v0.5/JuMP/src/JuMPContainer.jl:110
```

**Comment by mlubin** [comment]
@blegat

**Comment by blegat** [comment]
When I fix this first `MethodError` then I get
```
ERROR: LoadError: KeyError: key :model not found
 in getindex at ./dict.jl:688 [inlined]
 in getmeta(::JuMP.JuMPArray{JuMP.NonlinearExpression,1,Tuple{UnitRange{Int64}}}, ::Symbol) at /home/blegat/.julia/v0.5/JuMP/src/JuMPContainer.jl:101
 in _mapInner(::JuMP.#_getValue, ::JuMP.JuMPArray{JuMP.NonlinearExpression,1,Tuple{UnitRange{Int64}}}) at /home/blegat/.julia/v0.5/JuMP/src/JuMPContainer.jl:132
 in _map(::Function, ::JuMP.JuMPArray{JuMP.NonlinearExpression,1,Tuple{UnitRange{Int64}}}) at /home/blegat/.julia/v0.5/JuMP/src/JuMPContainer.jl:151
 in getvalue(::JuMP.JuMPArray{JuMP.NonlinearExpression,1,Tuple{UnitRange{Int64}}}) at /home/blegat/.julia/v0.5/JuMP/src/JuMPContainer.jl:110
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/blegat/.julia/v0.5/JuMP/test/runtests.jl, in expression starting on line 32
```
Indeed, there is no `pushmeta!($variable, :model, $m)`, ...
@mlubin Is this somethings missing from `macro.jl` ?

**Comment by mlubin** [comment]
I don't know much about ``pushmeta!`` but this only ever been called for collections of variables so it's not correct to assume that the metadata exists for other types of collections.

**Comment by blegat** [comment]
Ok, then I have just called the expression "__anon__", see #966 :)

**Comment by chkwon** [comment]
After `Pkg.checkout("JuMP")`,

```julia
julia> getvalue(F)
Error showing value of type JuMP.JuMPArray{Float64,1,Tuple{UnitRange{Int64}}}:
ERROR: KeyError: key :model not found
 in getindex at ./dict.jl:688 [inlined]
 in getmeta(::JuMP.JuMPArray{Float64,1,Tuple{UnitRange{Int64}}}, ::Symbol) at /Users/chkwon/.julia/v0.5/JuMP/src/JuMPContainer.jl:101
 in val_str(::Type{T}, ::JuMP.JuMPArray{Float64,1,Tuple{UnitRange{Int64}}}) at /Users/chkwon/.julia/v0.5/JuMP/src/print.jl:555
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::JuMP.JuMPArray{Float64,1,Tuple{UnitRange{Int64}}}) at ./REPL.jl:132
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::JuMP.JuMPArray{Float64,1,Tuple{UnitRange{Int64}}}) at ./REPL.jl:135
 in display(::JuMP.JuMPArray{Float64,1,Tuple{UnitRange{Int64}}}) at ./multimedia.jl:143
 in print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at ./REPL.jl:154
 in print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at ./REPL.jl:139
 in (::Base.REPL.##22#23{Bool,Base.REPL.##33#42{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:652
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at ./LineEdit.jl:1579
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in run_frontend(::Base.REPL.LineEditREPL, ::Base.REPL.REPLBackendRef) at ./REPL.jl:903
 in run_repl(::Base.REPL.LineEditREPL, ::Base.##930#931) at ./REPL.jl:188
 in _start() at ./client.jl:360
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
```

While `getvalue(F)` returns the value correctly, it has an issue in REPL.

**Comment by blegat** [comment]
When you print a `JuMPContainer` of `Variable` you get:
```
x[i] ≥ 0 ∀ i ∈ {1,2,3,4}
```
When you print a `JuMPContainer` of `NLexpression` you get:
```
JuMP.JuMPArray{JuMP.NonlinearExpression,1,Tuple{UnitRange{Int64}}}(JuMP.NonlinearExpression["Reference to nonlinear expression #1","Reference to nonlinear expression #2","Reference to nonlinear expression #3","Reference to nonlinear expression #4"],(1:4,),(Dict{Int64,Int64}(),),Dict{Symbol,Any}())
```
because `show` is not overwritten for this type.
When you print a `JuMPContainer` of `Float64` you get:
```
x: 1 dimensions:
[1] = NaN
[2] = NaN
[3] = NaN
[4] = NaN
```
but of course, if this `JuMPContainer` of `Float64` didn't come from a `JuMPContainer` of `Variable`, it hasn't got the `printdata` required to do that :(
We can call it `__anon__` again but here we also [need](https://github.com/JuliaOpt/JuMP.jl/blob/d12e8fce2a03bc40941899ba619550b606ec706a/src/print.jl#L564) `indexsets` that is in `printdata`.

**Comment by joehuchette** [comment]
I'm willing to rethink the ``printdata`` stuff; it's hacky and there are corner cases that break it pretty badly (like here). We should start by deciding what we think the behavior should be for each case.

**Comment by mlubin** [comment]
I'm not heavily invested in printing, so I'll leave it up to you.

**Comment by blegat** [comment]
Variables
======
When you create a variable with `@variable`, its name is either `__anon__` or the name you give. What is returned is either `Variable` (e.g. `@variable m`), `Array{Variable}` (`@variable m [1:3]` or `@variable m [1:3,1:3] SDP`) or `JuMPArray{Variable}` (e.g. `@variable m [1]` or `@variable m [2:3]`).
When you print a `Variable` you get `x`, when you print a `Array{Variable}` we let `Array` handle the printing and get:
```julia
julia> @variable m x[1:3] >= 0
3-element Array{JuMP.Variable,1}:
 x[1]
 x[2]
 x[3]
```
When you print a `JuMPArray{Variable}` you get:
```julia
julia> @variable m x[2:3] >= 0
x[i] ≥ 0 ∀ i ∈ {2,3}
julia> @variable m x[1]
x[i] free ∀ i ∈ {1}
```
To be consistent with the `JuMPArray`, we would like to add a specific `show` for `Array{Variable}` so that we get
```julia
julia> @variable m x[1:3] >= 0
x[i] ≥ 0 ∀ i ∈ {1,2,3}
```
However, I guess we do not have the information required to do that printing but we could do:
```julia
julia> @variable m x[1:3] >= 0
x[1] >= 0
x[2] >= 0
x[3] >= 0
```
or we could also simply do change `show` for `Variable` to have
```julia
julia> @variable m x[1:3] >= 0
3-element Array{JuMP.Variable,1}:
 x[1] >= 0
 x[2] >= 0
 x[3] >= 0
julia> @variable m x
x free
```
However, changing `show` for `Variable` might have side effect.

Constraints
======
When you create a variable with `@constraint`, , what is returned is either `ConstraintRef` (e.g. `@constraint m x >= 0`), `Array{ConstraintRef}` (`@constraint m [1:3] x >= 0`) or `JuMPArray{ConstraintRef}` (e.g. `@constraint m [1] x >= 0` or `@constraint m [2:3] x >= 0`).
When you print a `ConstraintRef` you get `x ≥ 0`, when you print a `Array{ConstraintRef}` we let `Array` handle the printing and get:
```julia
julia> @constraint m [i=1:3] x[i] >= 0
3-element Array{JuMP.ConstraintRef,1}:
 x[1] ≥ 0
 x[2] ≥ 0
 x[3] ≥ 0
```
When you print a `JuMPArray{ConstraintRef}` you get:
```julia
julia> @constraint m [i=2:3] x[i] >= 0
JuMP.JuMPArray{JuMP.ConstraintRef,1,Tuple{UnitRange{Int64}}}(JuMP.ConstraintRef[x[2] ≥ 0,x[3] ≥ 0],(2:3,),(Dict{Int64,Int64}(),),Dict{Symbol,Any}())
```

The printing of `ConstraintRef` seems to be already good. However, we could improve the printing of `Array{Variable}` and `JuMPArray{ConstraintRef}` to have
```julia
julia> @constraint m [i=1:3] x[i] >= 0
Linear Constraints
x[1] ≥ 0
x[2] ≥ 0
x[3] ≥ 0
julia> @constraint m [i=2:3] x[i] >= 0
Linear Constraints
x[2] ≥ 0 i = 2
x[3] ≥ 0 i = 3
```

@joehuchette What do you think ?

**Comment by mlubin** [comment]
@blegat, don't forget about ``JuMPDict``

**Comment by joehuchette** [comment]
Do we want to print variable bounds when we print variable (containers)? We should be consistent (I would vote no).

Honestly, I might be alright ditching the compact printing for containers ``Variable``s altogether, and just print each ``Variable`` on its own line. This would simplify the code considerably.

The changes to the constraint behavior seem good; not sure if the ``Linear Constraints`` part is necessary, and it may get confused when mixing constraint types in an array.

**Comment by blegat** [comment]
@mlubin In which case does `@variable` returns a `JuMPDict` ?

**Comment by mlubin** [comment]
@blegat when the set of indices is not a cartesian product across dimensions.
``@variable(m, x[i=1:N,j=1:i]); @variable(m, x[i=S,j=Q; condition(i,j)])`` etc

**Comment by blegat** [comment]
@joehuchette I agree, I have updated the proposition accordingly :)
